version: "3.7"
services:
    python:
        build:
            context: ./python
            dockerfile: Dockerfile
        
        networks:
            tap:
                ipv4_address: 10.0.100.3
        environment:
            CODE_PRODUCT: B093T7GQWB
            PYTHON_APP: amazonScraper.py
            HOST_LOGSTASH: 10.0.100.2
            PORT_LOGSTASH: 6000
            TIMEOUT_BEFORE_LOGSTASH: 100
            TIMEOUT_FETCH_ANOTHER_PAGE: 5
        depends_on:
            - logstash
    logstash:
        build:
            context: ./logstash
            dockerfile: Dockerfile
        networks:
            tap:
                ipv4_address: 10.0.100.2
        volumes:
            - $PWD/logstash/pipeline/:/usr/share/logstash/pipeline/
        ports:
            - 6000:6000
        depends_on:
            - kafka_server
    zookeeper:
        build:
            context: ./kafka
            dockerfile: Dockerfile
        networks: 
            tap:
                ipv4_address: 10.0.100.22
        ports:
            - 2181:2181
        environment: 
            KAFKA_ACTION: start-zk
    
    kafka_server:
        build:
            context: ./kafka
            dockerfile: Dockerfile
        networks: 
            tap:
                ipv4_address: 10.0.100.23
        ports:
            - 9092:9092
        environment: 
            KAFKA_ACTION: start-kafka
        depends_on: 
            - zookeeper

networks: 
    tap:
        name: tap
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24
    
  


        